Fixed. #1の課題が完了しました。
ddd503/objc-basic pull request #26
Opened 2017-08-06 14:35 UTC by ddd503

レビューをお願い致します。
githubの使い方等、不慣れな部分がありますので、使い方や設定等が間違っておりましたらお手数ですが、ご指摘をお願い致します。

2017-08-09 04:44 UTC, taguchi-k requested changes
@ddd503 
レビューしました。
指摘事項を確認して修正対応してください。

2017-08-09 04:44 UTC, taguchi-k commented on test_kadai/main.m
> +NSNumber *test4;
こちらmain関数内であれば初期値設定できます。

その他の変数も含めてmain関数内で定義しましょう。
この変数たちはmain関数のみでしか使っていないためです。
可能な限り変数のスコープは小さくしましょう。

2017-08-09 04:44 UTC, taguchi-k commented on test_kadai/main.m
> +BOOL test1 = YES;
変数名の `test1` ですが、それでは何を意味する変数かわからないです。
意味をもった命名をするようにしましょう。
他の変数も同様です。

2017-08-09 04:44 UTC, taguchi-k commented on test_kadai/main.m
> +        test4 = [NSNumber numberWithInt:10];
`numberWithInt:` はレガシー記法なので、モダン記法に修正しましょう。

2017-08-09 04:44 UTC, taguchi-k commented on test_kadai/main.m
> -    return 0;
ここは削除する必要ないと思います。

2017-08-09 04:44 UTC, taguchi-k commented on test_kadai/main.m
> +        NSLog(@"%ld", (long)test3);
ここは変数をキャストしなくても記述できます。
やり方は何通りかありますので、調べてみてください。

2017-08-09 10:50 UTC, taguchi-k requested changes

2017-08-09 10:50 UTC, taguchi-k commented on test_kadai/main.m
> -//
こちらは削除せず残しておきましょう。

2017-08-09 15:29 UTC, ddd503 reviewed
レビュー頂きありがとうございます。
ご指摘頂いた箇所を修正し、pushさせて頂きました。
お時間ある際に再度レビューをお願い致します。

2017-08-09 15:29 UTC, ddd503 commented on test_kadai/main.m
> -//
追加修正致しました。

2017-08-09 15:29 UTC, ddd503 commented on test_kadai/main.m
> +BOOL test1 = YES;
自分以外の人がわかりやすい変数名に変更致しました。

2017-08-09 15:29 UTC, ddd503 commented on test_kadai/main.m
> +NSNumber *test4;
全ての変数をmain関数内で初期値も含めて定義しました。

2017-08-09 15:29 UTC, ddd503 commented on test_kadai/main.m
> +        test4 = [NSNumber numberWithInt:10];
[NSNumber numberWithInt:10];と定義していたところを、
モダン記法の@10;という形に変更しました。

2017-08-09 15:29 UTC, ddd503 commented on test_kadai/main.m
> +        NSLog(@"%ld", (long)test3);
キャストをせずに、指定子をintとlongの両方の範囲に対応できる「%zd」に変更しました。

2017-08-09 15:29 UTC, ddd503 commented on test_kadai/main.m
> -    return 0;
「基本的には削除する必要がない」ということを理解せずに消してしまっておりました。
追加修正致しました。

2017-08-10 15:47 UTC, taguchi-k requested changes
@ddd503 
再レビューしましたのでご確認ください。

2017-08-10 15:47 UTC, taguchi-k commented on test_kadai/main.m
> +        BOOL Bool_value = YES;
変数名はlower camel caseにしましょう。
lower camel caseでの記載が一般的であるということと、
STVのコーディング規約にも定められているというのが理由です。
https://github.com/SmartTechVentures/Objective-C-style-guide

BOOL型の変数以外も同様です。

2017-08-10 15:47 UTC, taguchi-k commented on test_kadai/main.m
> +        NSString *NSstring_value = @"mojiretsu";
この場合の変数名は `string` でいいと思います。
その変数が利用される際の役割や状況に応じて適切な命名が変わってきます。
単純ではありますが経験を積んでも悩むことがある、奥が深いところだど思います。

＜本ケース＞
・NSStringであるかどうかは気にしなくていいのでNSプレフィックス不要
・何かの値であることも明確なので `value` 不要

2017-08-10 15:58 UTC, taguchi-k requested changes

2017-08-10 15:58 UTC, taguchi-k commented on test_kadai/main.m
> +//出力メソッド
`//` と コメント本文の間に半角スペースを入れてください。

2017-08-10 15:58 UTC, taguchi-k commented on test_kadai/main.m
> +
空白行が2行続いてしまうので削除しましょう。
可読性のために空白行1行使うのはOKです。

2017-08-10 17:43 UTC, ddd503 commented
@taguchi-k 
ご指摘頂いた箇所を修正し、push致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-10 17:43 UTC, ddd503 commented on test_kadai/main.m
> +//出力メソッド
修正致しました。

2017-08-10 17:43 UTC, ddd503 commented on test_kadai/main.m
> +
2行空いている箇所を可読性を考慮した1行分の空行に変更致しました。

2017-08-10 17:43 UTC, ddd503 commented on test_kadai/main.m
> +        NSString *NSstring_value = @"mojiretsu";
今後、他の方のコードなどを見ながら、変数の命名規則に慣れて行きたいと思います。
修正致しました。

2017-08-10 17:43 UTC, ddd503 commented on test_kadai/main.m
> +        BOOL Bool_value = YES;
コーディング規約を確認し、変数名を変更致しました。

2017-08-13 07:47 UTC, taguchi-k commented
@ddd503 
レビューOKです。マージしてください。
その後Issuesをクローズしてください。

2017-08-13 12:57 UTC, merged

2017-08-13 12:57 UTC, ddd503 commented
@taguchi-k 
レビュー頂き、ありがとうございます。
マージ致します。