Fiexd. #2の課題が完了しました。
ddd503/objc-basic pull request #33
Opened 2017-08-14 08:23 UTC by ddd503

@taguchi-k
重ね重ね申し訳ございません。
#1とは別プロジェクトにて作成致しました。
レビューをお願い致します。

2017-08-15 03:13 UTC, taguchi-k requested changes
@ddd503 
レビューしました。
確認・対応お願いします。

2017-08-15 03:13 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSArray *fruitsArray;
変数の宣言と初期化は可能な限り同時に行いましょう。
宣言から値を設定するまでの間に予期せぬ値が入る可能性を排除するためです。

2017-08-15 03:13 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        fruitsArray = [NSArray arrayWithObjects:@"りんご",@"バナナ",@"ぶどう",nil];
レガシーな記法になっているので、モダン記法に修正してください。

2017-08-15 03:13 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        fruitsColorArray = [NSDictionary dictionaryWithObjectsAndKeys:
レガシーな記法になっているので、モダン記法に修正してください。

2017-08-15 03:13 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSLog(@"%@", [fruitsColorArray objectForKey:@"りんご"]);
レガシーな記法になっているので、モダン記法に修正してください。

2017-08-15 16:40 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSArray *fruitsArray;
変数の宣言と同時に初期化を行うように修正致しました。

2017-08-15 16:40 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        fruitsArray = [NSArray arrayWithObjects:@"りんご",@"バナナ",@"ぶどう",nil];
fruitsArray = @[@"りんご",@"バナナ",@"ぶどう"];
上記のような記法に修正致しました。

2017-08-15 16:40 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        fruitsColorArray = [NSDictionary dictionaryWithObjectsAndKeys:
fruitsColorArray = @{@"りんご":@"赤色",@"バナナ":@"黄色",@"ぶどう":@"紫色"};
上記のような記法に修正致しました。

2017-08-15 16:40 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSLog(@"%@", [fruitsColorArray objectForKey:@"りんご"]);
fruitsColorArray[@"りんご"]
上記のような記法に修正致しました。

2017-08-15 18:34 UTC, ddd503 commented
@taguchi-k 
レビューにてご指摘頂いた点を修正致しました。
お時間ある際に再度レビューをお願いします。

2017-08-17 04:57 UTC, taguchi-k requested changes
@ddd503 
再レビューしました。

2017-08-17 04:57 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSDictionary *fruitsColorArray = @{@"りんご":@"赤色",@"バナナ":@"黄色",@"ぶどう":@"紫色"};
`Array`ではなく`Dictionary`等辞書型であることがわかる変数名のほうがいいと思います。

2017-08-17 20:09 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSDictionary *fruitsColorArray = @{@"りんご":@"赤色",@"バナナ":@"黄色",@"ぶどう":@"紫色"};
Array の部分をDictionaryに変更致しました。

2017-08-17 20:14 UTC, ddd503 commented
@taguchi-k 
レビューにてご指摘頂いた、変数名に関する箇所を修正致しました。
お時間ある際に再度レビューをお願いします。

2017-08-18 04:13 UTC, taguchi-k requested changes
レビューしましたので対応お願いします。

2017-08-18 04:13 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSArray *fruitsArray = @[@"りんご",@"バナナ",@"ぶどう"];
可読性のために、カンマの後に半角スペースを入れてください。

（今後の話ですが）プロジェクトのコーディング規約がある場合はそちらを優先してください。

2017-08-18 04:13 UTC, taguchi-k commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSDictionary *fruitsColorDictionary = @{@"りんご":@"赤色",@"バナナ":@"黄色",@"ぶどう":@"紫色"};
1行が長くなっているのでカンマの後はそれぞれ改行してもいいと思います。
細かい文字数はプロジェクトによって異なりますが、1行80文字くらいを超えないようにすることが多いです。

2017-08-18 23:09 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSArray *fruitsArray = @[@"りんご",@"バナナ",@"ぶどう"];
スペースを追加いたしました。

2017-08-18 23:12 UTC, ddd503 commented on STVProject1-1-2/STVProject1-1-2/main.m
> +        NSDictionary *fruitsColorDictionary = @{@"りんご":@"赤色",@"バナナ":@"黄色",@"ぶどう":@"紫色"};
改行追加いたしました。

2017-08-18 23:15 UTC, ddd503 commented
@taguchi-k
レビューにてご指摘頂いた点を修正させて頂きました。
お時間ある際にレビューをお願い致します。

2017-08-20 06:08 UTC, taguchi-k commented
レビューOKです。お疲れ様でした！
プルリクマージして、issuesをクローズしてください。

2017-08-20 06:59 UTC, ddd503 commented
@taguchi-k 
ご確認ありがとうございます。
マージさせて頂きます。

2017-08-20 06:59 UTC, merged