Fiexd. #3の課題が完了しました。
ddd503/objc-basic pull request #34
Opened 2017-08-14 08:35 UTC by ddd503

@taguchi-k
重ね重ね申し訳ございません。
#1とは別プロジェクトにて作成致しました。
レビューをお願い致します。

2017-08-15 04:25 UTC, taguchi-k requested changes
@ddd503 
レビューしました。確認・対応をお願いします。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSInteger testPoint1 = 80;
testPoint1〜3は適切な変数名に修正してください。
例えば、testPoint1は合格者を表す変数名にするとか、何のテストの点数なのかを表す変数名にするとか、という感じです。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSArray *numberArray = [NSArray arrayWithObjects:@1,@2,@3,@4,@5,@6,@7,@8,@9, nil];
レガシーな記法になっているので、モダン記法に修正してください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        if(testPoint1 >= 60){
60はマジックナンバーになっているので、定数化しましょう。
その際適切な命名をしてください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        if(testPoint2 >= 80){
80はマジックナンバーになっているので、定数化しましょう。
その際適切な命名をしてください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        }else if(testPoint2 >= 60){
60はマジックナンバーになっているので、定数化しましょう。
その際適切な命名をしてください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSString *result = (testPoint3 >= 60)?@"合格":@"不合格";
60はマジックナンバーになっているので、定数化しましょう。
その際適切な命名をしてください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        }else{
else と 括弧の間に半角スペースを入れてください。
（プロジェクトによって推奨される書き方が異なる場合があるので、そのプロジェクトのコーディング規約で定義されていたらそちらに従うようにしましょう）

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSString *result = (testPoint3 >= 60)?@"合格":@"不合格";
`?` の前後と `:`の前後に半角スペースを入れましょう。

```
NSString *result = (testPoint3 >= 60) ? @"合格" : @"不合格";
```

（プロジェクトによって推奨される書き方が異なる場合があるので、そのプロジェクトのコーディング規約で定義されていたらそちらに従うようにしましょう）

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        for(NSInteger i=0; i<=10; i++){
`=`の前後、`<=`の前後に半角スペースを入れてください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            plusCount = i*2;
`*`の前後に半角スペースを入れてください。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            NSLog(@"合格");
ここだけではなく`NSLog`の箇所全体に対して言えるのですが、ただ結果が出力されるだけで何の結果かわからないです。（特に今回は複数ログが出力されるため）
` NSLog(@"●●の判定結果: 合格");`のような形にしてあげるとログが見やすくなると思います。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSArray *numberArray = [NSArray arrayWithObjects:@1,@2,@3,@4,@5,@6,@7,@8,@9, nil];
【参考：修正不要です】
`numberArray`でも配列であることがわかる変数名なのでOKなのですが、その他に`numbers`のように複数形にする命名も一般的に使われていますので覚えておいてください。
あとは`numberList`のような命名パターンもあるかなと思います。

2017-08-15 04:25 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        switch (numberCheck) {
`numberCheck `という`NSInteger `の変数が何を表しているのかよくわからないです。
switch文で列挙する場合は`NS_ENUM`を利用した列挙型で定義すべきだと思います。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        switch (numberCheck) {
typedef NS_ENUM(NSInteger, MethodNumberEnum) {
            MethodNumber0 = 0,
            MethodNumber1 = 1,
            MethodNumber2 = 2,
        };
上記の記法に修正致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        for(NSInteger i=0; i<=10; i++){
記法を修正致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            plusCount = i*2;
記法を修正致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSString *result = (testPoint3 >= 60)?@"合格":@"不合格";
記法を修正致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSString *result = (testPoint3 >= 60)?@"合格":@"不合格";
マジックナンバーは全て定数化致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        }else if(testPoint2 >= 60){
マジックナンバーは全て定数化致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        if(testPoint2 >= 80){
テストの合格点を揃えるため、80→60に値を変更致しました。
マジックナンバーは全て定数化致しました。

2017-08-15 18:28 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        }else{
他の部分も合わせて、半角スペースを挿入致しました。

2017-08-15 18:29 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            NSLog(@"合格");
全ての出力結果を修正致しました。

2017-08-15 18:29 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        if(testPoint1 >= 60){
以前お教え頂いた、コード規約に沿って定数を作成致しました。

2017-08-15 18:29 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSArray *numberArray = [NSArray arrayWithObjects:@1,@2,@3,@4,@5,@6,@7,@8,@9, nil];
ご指摘頂きありがとうございます。
今後の変数命名の参考と致します。

2017-08-15 18:29 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSArray *numberArray = [NSArray arrayWithObjects:@1,@2,@3,@4,@5,@6,@7,@8,@9, nil];
NSArray *numberArray = @[@1,@2,@3,@4,@5,@6,@7,@8,@9];
上記の記法に修正致しました。

2017-08-15 18:29 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSInteger testPoint1 = 80;
何のテストの点数か、という点をわかりやすくする変数名に変更致しました。

2017-08-15 18:35 UTC, ddd503 commented
@taguchi-k 
レビューにてご指摘頂いた点を修正致しました。
お時間ある際に再度レビューをお願いします。

2017-08-18 04:56 UTC, taguchi-k requested changes
@ddd503 
レビューしました。あともう一息です！
確認・対応してください。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSArray *numberArray = @[@1,@2,@3,@4,@5,@6,@7,@8,@9];
カンマの後に半角スペースを入れましょう。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSInteger MethodNumber = 2;
`NSInteger `ではなく`NS_ENUM`で定義した型にしましょう。
何の値か明確になる・予期せぬ値の代入を予防するためです。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        static NSInteger *const PassTestScore = 60;
警告が出ているので理由を調べて修正してください。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        static NSInteger *const RepeatTestScore = 30;
警告が出ているので理由を調べて修正してください。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            MethodNumber0 = 0,
0からの連番の場合、明示的な数値の代入は不要です。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            MethodNumber0 = 0,
何を表す命名なのかわかりづらいです。
前回の止まれ・進め、のほうが命名しやすいかもしれませんね。

2017-08-18 04:56 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        if (englishTestScore >= (long)PassTestScore) {
`long`へのキャストは不要です。
別途指摘している警告への対応後改めて確認してみてください。

他の`long`へのキャスト部分も同様です。

2017-08-19 10:38 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSArray *numberArray = @[@1,@2,@3,@4,@5,@6,@7,@8,@9];
スペースを追加致しました。

2017-08-19 10:38 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        NSInteger MethodNumber = 2;
NS_ENUM内にて変数を定義致しました。

2017-08-19 10:39 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        static NSInteger *const PassTestScore = 60;
定数の定義の記載に誤りがありました。
static const NSInteger  PassTestScore = 60;

上記のように修正致しました。

2017-08-19 10:39 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        static NSInteger *const RepeatTestScore = 30;
定数の定義の記載に誤りがありました。
static const NSInteger  RepeatTestScore = 30;

上記のように修正致しました。

2017-08-19 10:39 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            MethodNumber0 = 0,
0からの連番のため、数値代入を省略致しました。

2017-08-19 10:39 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            MethodNumber0 = 0,
変数に入る値によって、止まれ、進めなどの指示を表示するメソッド内容に変更致しました。

2017-08-19 10:39 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +        if (englishTestScore >= (long)PassTestScore) {
定数の定義部分の修正後、longへのキャストを削除しても警告が出なくなっておりました。
定義の方法を今一度見直しておこうと思います。

2017-08-19 10:41 UTC, ddd503 commented
@taguchi-k
レビューにてご指摘頂いた点を修正致しました。
お時間ある際に再度レビューをお願いします。

2017-08-20 06:21 UTC, taguchi-k requested changes
@ddd503 
一点だけコメントしました！

2017-08-20 06:21 UTC, taguchi-k commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            SignalAlertNumber = 2
`NS_ENUM`内で変数を定義して代入するような使い方はしないので、`NS_ENUM`外で変数を定義してください。

おそらく`SignalAlertNumber `を変数として定義しようとしているのだと思いますが、この実装だと`SignalAlertNumber `は`SignalAlertEnum `の要素の１つということになります。
`2`の要素が`StopSignalAlert `と`SignalAlertNumber `2つ存在している状態です。

```
// 参考
SignalAlertEnum SignalAlertNumber = StopSignalAlert;
```

2017-08-20 07:12 UTC, ddd503 commented on STVProject1-1-3/STVProject1-1-3/main.m
> +            SignalAlertNumber = 2
@taguchi-k 
NS_ENUM内で定義した変数をNS_ENUM外で定義したSignalAlertNumberに代入するような形に修正致しました。

2017-08-20 07:15 UTC, ddd503 commented
@taguchi-k 
レビュー頂きました箇所を修正させて頂きました。
お時間ある際に再度レビューをお願い致します。

2017-08-20 14:29 UTC, taguchi-k commented
@ddd503
レビューOKです。お疲れ様でした！
プルリクマージして、issuesをクローズしてください。

2017-08-20 15:53 UTC, ddd503 commented
@taguchi-k 
ご確認頂きありがとうございます。
マージさせて頂きます。

2017-08-20 15:53 UTC, merged