Fiexd. #4の課題が完了しました。
ddd503/objc-basic pull request #35
Opened 2017-08-14 08:41 UTC by ddd503

@taguchi-k
重ね重ね申し訳ございません。
#1とは別プロジェクトにて作成致しました。
レビューをお願い致します。

2017-08-19 13:27 UTC, ddd503 commented
@taguchi-k
レビューを頂く前に申し訳ございませんが、#1~#3にてご指摘を受けた内容を#4においても修正させて頂きました。
お時間ある際にレビューをお願い致します。

2017-08-20 06:34 UTC, taguchi-k requested changes
@ddd503 
レビューしましたので確認・対応してください。

2017-08-20 06:34 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +@implementation Account
`Account`クラスはヘッダファイル・実装ファイルともに別ファイルで作成してください。

2017-08-20 06:34 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.h
> +//  main.h
別途指摘のとおり`Account`クラスを別ファイルで作成するので、`main.h`ではなく`Account.h`が必要ですね。

2017-08-20 06:34 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +    NSArray *employeeName = @[@"鈴木あやか", @"佐藤春彦", @"渡辺直美", @"木村拓哉", @"加藤浩次", @"若林里美"];
氏名は`Account`クラスのプロパティとして定義してください。
氏名以外も同様です。

2017-08-20 06:34 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        id classObject;
`Account `型であることが明確なので、`id`型を使用しないでください。
宣言と同時に初期化していいと思います。

2017-08-20 10:11 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +@implementation Account
別ファイルにて作成致しました。

2017-08-20 10:11 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +    NSArray *employeeName = @[@"鈴木あやか", @"佐藤春彦", @"渡辺直美", @"木村拓哉", @"加藤浩次", @"若林里美"];
Accountクラスにてプロパティ定義を行いました。

2017-08-20 10:11 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        id classObject;
Account *classObject = [[Account alloc] init];
上記のように宣言と初期化を同時に行いました。

2017-08-20 10:11 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.h
> +//  main.h
Account.hを作成し、main.mにインポート致しました。

2017-08-20 10:12 UTC, ddd503 commented
@taguchi-k 
レビュー頂いた箇所を修正致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-20 16:30 UTC, taguchi-k requested changes
レビューしましたので確認・対応してください。

2017-08-20 16:30 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.h
> +//  main.h
`main.h`は不要です。

2017-08-20 16:30 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.h
> +#ifndef Account_h
9〜12行目まで不要です。
`Foundation`を`import`すればOKです。

2017-08-20 16:30 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.h
> +// プロパティを定義
こちらで定義しているプロパティは外部から利用していないので、実装ファイルに定義しましょう。

2017-08-20 16:30 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.h
> +@property NSArray *employeeName;
氏名等のプロパティを配列で定義せず、単体で定義しましょう。
外部から利用する際に`Account`型のインスタンスの配列を使うようにしてください。
`Account`クラスはあくまでもアカウントをモデル化したものであることを意識してもらうといいと思います。

2017-08-20 16:30 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +    _employeeName = @[@"鈴木あやか", @"佐藤春彦", @"渡辺直美", @"木村拓哉", @"加藤浩次", @"若林里美"];
プロパティには`self`でアクセスするようにしてください。
独自getterやsetterが定義されている場合それらが呼ばれるようにするためです。
他も同様です。

2017-08-20 16:30 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeelist{
ここは自分のプロパティを出力するだけのメソッドにしたほうがいいかもしれませんね。
今回の場合であればプロパティへの値のセットはイニシャライザ作ってそこでセットしてあげればいいと思います。

2017-08-21 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.h
> +#ifndef Account_h
9~12行目を削除し、
#import <Foundation/Foundation.h>
を追記致しました。

2017-08-21 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.h
> +// プロパティを定義
Account.mファイル内に定義致しました。

2017-08-21 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.h
> +@property NSArray *employeeName;
個人情報用プロパティを単体で定義し、別途配列を定義致しました。
ただ、「Account型のインスタンスの配列を使うようにしてください。」という部分の理解に不安がありますので、一度レビューをお願い致します。

2017-08-21 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeelist{
別途イニシャライザを定義致しました。

2017-08-21 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +    _employeeName = @[@"鈴木あやか", @"佐藤春彦", @"渡辺直美", @"木村拓哉", @"加藤浩次", @"若林里美"];
_ではなくselfでアクセスするように変更いたしました。

2017-08-21 16:29 UTC, ddd503 commented
@taguchi-k 
レビュー頂いた箇所を修正致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-22 04:53 UTC, taguchi-k requested changes
@ddd503 
レビューしましたので確認してください。

2017-08-22 04:53 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +@property NSArray *employeeNameList;
`NSArray`のプロパティは全て不要です。

2017-08-22 04:53 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +- (id)init {
引数で各プロパティを設定するようにすると、インスタンス化のとき便利です。

2017-08-22 04:53 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeeList{
このメソッドは自身のプロパティを出力するだけのメソッドでいいです。
（性別の判定は必要）

2017-08-22 04:53 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        Account *classObject = [[Account alloc] init];
ここで`Account`型のインスタンスを一つだけ作るのではなく、社員分作ってみてはいかがでしょうか？

2017-08-22 09:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +@property NSArray *employeeNameList;
NSArrayのプロパティを削除し、指定イニシャライザにて社員情報を設定するようにしました。

2017-08-22 09:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +- (id)init {
この箇所に関してご質問がございます。
指定イニシャライザを作成し、main.mの実行タイミングで引数を渡そうとしているのですが、
指定イニシャライザにアクセスできずに詰まっております。
やり方として間違った方法なのでしょうか？

2017-08-22 09:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeeList{
出力のみのメソッドに変更致しました。

2017-08-22 09:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        Account *classObject = [[Account alloc] init];
作成したイニシャライザにアクセスできずに詰まっております。

2017-08-22 09:27 UTC, ddd503 commented
@taguchi-k 
レビューにてご指摘頂いた点を修正致しました。
ただ、変数の引数を指定したイニシャライズにアクセスできず、「複数の社員情報の作成」ができずに詰まっております。
大変恐れ入りますが、一度レビューをお願いできますでしょうか。

2017-08-22 10:24 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        Account *classObject = [[Account alloc] init];
イニシャライザが公開されていませんよ。

2017-08-22 14:39 UTC, taguchi-k requested changes
レビューしましたので確認してください。

2017-08-22 14:39 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +- (id)initName:(NSString*)name initAge:(NSNumber*)age initSex:(NSString*)sex initGoodLanguage:(NSString*)goodlanguage {
【want】
口頭でも指摘しましたが、戻り値は`instancetype`のほうがいいと思います。
`id`でも間違えではないので余裕があれば対応してください。

2017-08-22 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +- (id)initName:(NSString*)name initAge:(NSNumber*)age initSex:(NSString*)sex initGoodLanguage:(NSString*)goodlanguage {
instancetypeにて実装させて頂きました。
idとの違いに関しては、今一度確認し、理解しておきたいと思います。

2017-08-22 16:26 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        Account *classObject = [[Account alloc] init];
ご指摘頂いたように、イニシャライザを公開し、引数を渡しました。

2017-08-22 16:28 UTC, ddd503 commented
@taguchi-k 
ご指摘頂いた箇所を修正させて頂きました。
お時間ある際に再度レビューをお願い致します。

2017-08-23 04:49 UTC, taguchi-k requested changes
@ddd503 レビューしました！

2017-08-23 04:49 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        for(int i=0; i<employeeList.count; i++){
ここは`for-in`で書けます。
パフォーマンスの観点とコードがシンプルになる観点から、可能であればこちらを使いましょう。

2017-08-23 04:49 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        Account *classObject = [[Account alloc] init];
`classObject `は不要です。

2017-08-23 04:49 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +    if (self != nil) {
`if (!self) `と書けます。
こちらが一般的かつコーディング規約で定められているの修正してください。

2017-08-23 04:49 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeeList:(Account*)account{
引数不要です。

2017-08-23 05:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +    if (self != nil) {
こちら、if (!self)に修正すると正しくイニシャライズできなくなってしまったため、
STVのコーディング規約にあった、if (self)を使用しておりますが、書き方として問題があるのでしょうか？

2017-08-23 05:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeeList:(Account*)account{
引数を使った渡し方ではなく、メソッドに直接インスタンスを送るように修正しました。

2017-08-23 05:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        Account *classObject = [[Account alloc] init];
classObjectを削除し、作成したインスタンスを直接出力メソッドに飛ばしました。

2017-08-23 05:25 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/main.m
> +        for(int i=0; i<employeeList.count; i++){
for-in の書き方に直しました。

2017-08-23 05:27 UTC, ddd503 commented
@taguchi-k
ご指摘頂いた箇所を修正させて頂きました。
イニシャライズの部分で一点ご質問させて頂いております。
お時間ある際に再度レビューをお願い致します。

2017-08-23 05:42 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +    if (self != nil) {
すいません、!いらないです。

2017-08-23 06:21 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +    if (self != nil) {
@taguchi-k 
かしこまりました。
では、現在の、if (self)のまま、レビューをお願い致します。

2017-08-24 00:56 UTC, taguchi-k reviewed
@ddd503 
レビューOKです！お疲れ様でした！

※軽微な指摘をしていますのでご確認ください。
　対応不要ですので進捗を進めるようにしてください。

2017-08-24 00:56 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +- (instancetype)initName:(NSString*)name initAge:(NSNumber*)age initSex:(NSString*)sex initGoodLanguage:(NSString*)goodlanguage {
【対応不要です：参考】
`initName`は`initWithName`とするのがObjective-Cだと一般的です。
各引数の`init`は冗長かなと感じました。

参考までに、自分だったら下記のように書きます。

```
- (instancetype)initWithName: (NSString *)name
                         age: (NSInteger)age
                      gender: (NSString *)gender
            favoriteLanguage: (NSString *)favoriteLanguage
```

2017-08-24 00:56 UTC, taguchi-k commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeeList{
【対応不要です：参考】
本メソッド自体ではリストを出力していないので、メソッド名最後の`List`は不要だと思います。

2017-08-24 03:33 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +- (instancetype)initName:(NSString*)name initAge:(NSNumber*)age initSex:(NSString*)sex initGoodLanguage:(NSString*)goodlanguage {
ご指摘ありがとうございます。
今後は命名規則をさらに意識して書いていきます。

2017-08-24 03:34 UTC, ddd503 commented on STVProject1-1-4/STVProject1-1-4/Account.m
> +-(void)outputEmployeeList{
ご指摘ありがとうございます。
今後はメソッドの内容を明確にした命名規則を意識していきます。

2017-08-24 03:35 UTC, ddd503 commented
@taguchi-k 
レビューありがとうございます。
マージさせて頂きます。

2017-08-24 03:36 UTC, merged