Fiexd. #5の課題を提出致します。
ddd503/objc-basic pull request #36
Opened 2017-08-17 09:18 UTC by ddd503

@taguchi-k
Fiexd. #5の課題を一度提出致します。
目的結果の出力ができていない状態となり、申し訳ございませんが、レビューをお願い致します。

2017-08-20 07:02 UTC, taguchi-k requested changes
@ddd503 
レビューしました。
`delegate`に関する理解がごっちゃになっていそうなので、下記リンク先を参考に改めて実装してみてください。
http://qiita.com/ktaguchi/items/4622d01a741ed47c20f8

2017-08-20 07:02 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/main.m
> +@interface Account()
`Account`クラスについては前課題で指摘のとおり別ファイルで定義してください。

2017-08-20 07:02 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/main.m
> +- (void)インターンに参加する
業務でプログラミングする際は、メソッド名や変数名にマルチバイト文字を使用しないでください。
上記コーディング規約で定められていることがほとんどであるためです。

2017-08-20 07:02 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/delegateFile.h
> +//  delegateFile.h
ファイル名をクラス名と合わせましょう。
`FavoriteProgrammingLanguage.h`

2017-08-20 07:02 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/delegateFile.m
> +@interface FavoriteProgrammingLanguage () <FavoriteProgrammingLanguageDelegate>
本クラスは`delegate`される側ではなく`delegate`する側です。

2017-08-20 15:46 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/delegateFile.m
> +@interface FavoriteProgrammingLanguage () <FavoriteProgrammingLanguageDelegate>
頂いたURLを参考に、デリゲートされる側とする側を整理致しました。

2017-08-20 15:46 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/delegateFile.h
> +//  delegateFile.h
FavoriteProgrammingLanguageクラスを新たに作成致しました。

2017-08-20 15:46 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/main.m
> +- (void)インターンに参加する
頂いたコーディング規約に沿って、命令し直しました。

2017-08-20 15:46 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/main.m
> +@interface Account()
別ファイルにて作成致しました。

2017-08-20 15:48 UTC, ddd503 commented
@taguchi-k 
頂いたURLを元に、今一度デリゲート機能を確認しました。
お時間ある際に再度レビューをお願い致します。

2017-08-20 17:42 UTC, taguchi-k requested changes
こちらは前課題の修正の反映もしてください。

まだdelegateする側とされる側がごっちゃになっているようです。
再レビューしたので確認・対応してください。

2017-08-20 17:42 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/Account.h
> +//  Account.h
【備忘】
前課題の修正を反映するようにしてください。

2017-08-20 17:42 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/Account.m
> +//  Account.m
【備忘】
前課題の修正を反映するようにしてください。

2017-08-20 17:42 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/Account.m
> +int main(int argc, const char * argv[]) {
`main.m`に実装してください。

2017-08-20 17:42 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/Account.h
> +@protocol FavoriteProgrammingLanguageDelegate <NSObject>
`Account`クラスはdelegateされる側です。

2017-08-20 17:42 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/FavoriteProgrammingLanguage.m
> +    [self canDoObjc];
これだとdelegateオブジェクトではなく、自分自身が`canDoObjc `メソッドを呼んでいます。

2017-08-22 01:39 UTC, ddd503 commented
@taguchi-k 
ご指摘頂いた内容にて修正を行っておりましたが、Account.mにて、定義したデリゲートインスタンスを呼び出せずに詰まってしまっております。
大変お手数をお掛け致しますが、再度レビューをお願いできますでしょうか。

2017-08-24 16:25 UTC, taguchi-k commented
@ddd503
前課題の修正をこちらにも反映してください。

2017-08-25 01:21 UTC, ddd503 commented
@taguchi-k 
申し訳ございません、「前課題の修正の反映」に関して、具体的な修正点が掴めずにおります。
テーブルビューの実装などを参考に今一度修正を行いましたが、課題目的の動作が実行できないでおります。

合わせて、下記の点をご質問させて頂きたいです。
self.delegate respondsToSelector:@selector(オプショナルメソッド名:)
上記のコードは、「オプショナルメソッド実行の可否を確認している」との記載があったのですが、これは必須の処理なのでしょうか？
この処理を通した時にオプショナルメソッドが動作せず止まってしまいます。

2017-08-25 04:43 UTC, taguchi-k commented
@ddd503 
> 「前課題の修正の反映」
1.1.4ですでに`Account`クラスを作っているので、それを使いまわしてもらったうえで本課題の実装をしてもらえればという意図でした。
別途作成しても実装可能なので、使いまわさなくても構いません。

> オプショナルメソッド実行の可否を確認
こちらは必須です。
delegateオブジェクトが該当メソッドを実装している保証がないためです。
動作しないのは実装上の問題です。

2017-08-25 04:55 UTC, taguchi-k requested changes

2017-08-25 04:55 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/main.h
> +//  main.h
本ファイルは不要です。

2017-08-25 04:55 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/Account.h
> +@property (strong, nonatomic) Account *account;
このプロパティは何故定義しているのでしょうか？

2017-08-25 09:45 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/Account.h
> +@property (strong, nonatomic) Account *account;
必要のないプロパティでした。
削除致しました。

2017-08-25 09:45 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/main.h
> +//  main.h
削除致しました。

2017-08-25 09:48 UTC, ddd503 commented
@taguchi-k 
ご指摘頂いた箇所に加え、デリゲートメソッドを定義するファイルを間違えておりましたので、その部分を修正しましたところ、無事動作致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-25 09:55 UTC, ddd503 commented
@taguchi-k 
続けて失礼致します。
上記の変更に加え、前課題のクラス構成を参考にイニシャライズの戻り値の型を変更致しました。

2017-08-26 01:04 UTC, taguchi-k commented on STVProject1-1-5/STVProject1-1-5/FavoriteProgrammingLanguage.m
> +    if (self = [super init]) {
特に何もしないのであれば不要です。

2017-08-26 01:05 UTC, taguchi-k commented
@ddd503 
レビューOKです。お疲れ様でした！
一点指摘しているので確認だけしてください。

2017-08-26 04:13 UTC, ddd503 commented on STVProject1-1-5/STVProject1-1-5/FavoriteProgrammingLanguage.m
> +    if (self = [super init]) {
かしこまりました。
使用しない際は、無駄な記載をしないよう注意します。

2017-08-26 04:13 UTC, ddd503 commented
レビューありがとうございます。
マージさせて頂きます。

2017-08-26 04:13 UTC, merged