Fiexd. #6の課題が完了しました。
ddd503/objc-basic pull request #37
Opened 2017-08-19 16:10 UTC by ddd503

@taguchi-k
お時間ある際にレビューをお願い致します。

2017-08-22 03:08 UTC, ddd503 commented
@taguchi-k
レビュー前のタイミングで申し訳ございませんが、
以前の課題にてご指摘頂いた箇所を改めて修正させて頂きました。

2017-08-26 01:16 UTC, taguchi-k requested changes
@ddd503 
レビューしました。確認・対応してください。

2017-08-26 01:16 UTC, taguchi-k commented on STVProject2-1-1/STVProject2-1-1/ViewController.m
> +    self.resultLabel.text = @"Obj-C講座をスタートしました。";
テキストはベタ打ちせず、`Localizable.strings`で定義したものを利用してください。

2017-08-26 04:26 UTC, ddd503 commented on STVProject2-1-1/STVProject2-1-1/ViewController.m
> +    self.resultLabel.text = @"Obj-C講座をスタートしました。";
Localizable.stringsに定義したテキストを参照するよう、書き方を変更致しました。

2017-08-26 04:28 UTC, ddd503 commented
レビュー頂いた箇所を修正致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-27 04:08 UTC, taguchi-k commented on STVProject2-1-1/STVProject2-1-1/ViewController.m
> +    self.resultLabel.text = @"Obj-C講座をスタートしました。";
【修正不要】
下記利用したほうがコードが簡潔になると思います。
https://developer.apple.com/documentation/foundation/nslocalizedstring

2017-08-27 04:08 UTC, taguchi-k commented
@ddd503 
レビューOKです！

2017-08-27 05:10 UTC, ddd503 commented
@taguchi-k 
レビューありがとうございます。
マージさせて頂きます。

2017-08-27 05:10 UTC, merged