Fiexd. #7の課題が完了しました。
ddd503/objc-basic pull request #38
Opened 2017-08-19 16:16 UTC by ddd503

@taguchi-k
お時間ある際にレビューをお願い致します。

2017-08-22 03:11 UTC, ddd503 commented
@taguchi-k
レビュー前のタイミングで申し訳ございませんが、
以前の課題にてご指摘頂いた箇所を改めて修正させて頂きました。

2017-08-26 01:25 UTC, taguchi-k requested changes
@ddd503 
レビューしました。確認・対応してください。

2017-08-26 01:25 UTC, taguchi-k commented on STVProject2-1-2/STVProject2-1-2/ViewController.m
> +    self.foodImage.image = [UIImage imageNamed:@"AustrariaBeef"];
静的な画像の設定は`storyboard`でするようにしましょう。
Viewに関連するコードは可能な限り減らし、ソースコードの見通しをよくすることが狙いです。

※動的に変更する必要がある場合はその限りではありません。

2017-08-26 04:34 UTC, ddd503 commented on STVProject2-1-2/STVProject2-1-2/ViewController.m
> +    self.foodImage.image = [UIImage imageNamed:@"AustrariaBeef"];
今回は動的な仕様ではないため、画像のセットはストーリボード側にて実装するように修正致しました。

2017-08-26 04:35 UTC, ddd503 commented
@taguchi-k 
レビュー頂いた箇所を修正致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-27 04:13 UTC, taguchi-k commented
@ddd503 レビューOKです！

2017-08-27 05:11 UTC, ddd503 commented
@taguchi-k 
レビューありがとうございます。
マージさせて頂きます。

2017-08-27 05:11 UTC, merged