Fiexd. #8の課題が完了しました。
ddd503/objc-basic pull request #39
Opened 2017-08-19 16:24 UTC by ddd503

@taguchi-k
お時間ある際にレビューをお願い致します。

2017-08-22 03:29 UTC, ddd503 commented
@taguchi-k
レビュー前のタイミングで申し訳ございませんが、
以前の課題にてご指摘頂いた箇所を改めて修正させて頂きました。

2017-08-27 04:21 UTC, taguchi-k requested changes
@ddd503 
レビューしました。確認・対応してください。
（wantのものは余裕があれば対応してください）

2017-08-27 04:21 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +@property NSString * imageName;
このプロパティは何に使っているのでしょうか？

2017-08-27 04:21 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +- (void)didReceiveMemoryWarning {
【want】
利用しないのであれば削除して構わないです。
余計なコードがないほうが、コードの見通しが良くなります。

2017-08-27 04:21 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +    self.randomCount = arc4random_uniform((int)self.imageList.count);
`randomCount `は本メソッド内でしか利用しないのであれば、プロパティとして保持する必要がありません。

2017-08-27 04:21 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +    }
【want】
インデントがおかしいです。

2017-08-27 05:24 UTC, ddd503 commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +    }
失礼しました。
インデント位置を修正致しました。

2017-08-27 05:24 UTC, ddd503 commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +    self.randomCount = arc4random_uniform((int)self.imageList.count);
メソッド内にて生成し、使用するように変更致しました。

2017-08-27 05:24 UTC, ddd503 commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +- (void)didReceiveMemoryWarning {
ご指摘ありがとうございます。
利用していないため削除いたします。

2017-08-27 05:27 UTC, ddd503 commented
@taguchi-k 
レビュー頂いた箇所を修正致しました。
お時間ある際に再度レビューをお願い致します。

2017-08-27 06:22 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +@property NSString * imageName;
@ddd503 
こちらはいかがでしょうか？

2017-08-27 06:23 UTC, taguchi-k commented
@ddd503 
対応漏れがあるようなので確認してください。

2017-08-27 06:34 UTC, ddd503 commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +@property NSString * imageName;
失礼致しました。
メソッド内でのみ使用するため、内部で生成するように変更しましたが、
今一度見直すと、self.backgroundView.imageに直接ランダム値にて取得した画像名を代入することができるため、
必要のない変数でした。
修正対応致しました。

2017-08-27 06:36 UTC, ddd503 commented
@taguchi-k 
失礼致しました。
ご指摘頂いた点を修正致しました。
再度レビューをお願い致します。

2017-08-27 06:43 UTC, taguchi-k requested changes
@ddd503 
意図が伝わっていなかったようなので、再度レビューしました。

2017-08-27 06:43 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> -    int randomCount = arc4random_uniform((int)self.imageList.count);
@ddd503 
こちら削除していますが、`randomCount `を変数にセットして使っているこちらのほうが見やすいです。

2017-08-27 06:43 UTC, taguchi-k commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +@property NSString * imageName;
`@property NSString * imageName;`は利用していますか？

2017-08-27 06:54 UTC, ddd503 commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> -    int randomCount = arc4random_uniform((int)self.imageList.count);
変数を用意し、セットする記法に戻しました。

2017-08-27 06:54 UTC, ddd503 commented on STVProject2-1-3/STVProject2-1-3/ViewController.m
> +@property NSString * imageName;
意図を汲み取れず、失礼しました。
勘違いしておりました。
@property NSString * imageName;はどこでも使用しておりませんでした。
削除させて頂きました。

2017-08-27 06:56 UTC, ddd503 commented
@taguchi-k
意図を汲み取れず、失礼致しました。
ご指摘頂いた点を修正致しました。
再度レビューをお願い致します。

2017-08-27 07:15 UTC, taguchi-k commented
@ddd503 レビューOKです！

2017-08-27 07:20 UTC, ddd503 commented
@taguchi-k 
レビューありがとうございます。
マージさせて頂きます。

2017-08-27 07:20 UTC, merged