Fiexd. #9の課題が完了しました。
ddd503/objc-basic pull request #40
Opened 2017-08-22 02:59 UTC by ddd503

@taguchi-k
#9の課題が完了しました。
お時間ある際にレビューをお願い致します。

2017-08-27 05:41 UTC, ddd503 commented
以前の課題にてレビュー頂いた箇所を修正しております。
お時間ある際にレビューをお願い致します。

2017-08-28 04:44 UTC, taguchi-k requested changes
@ddd503 
レビューしました。確認・対応してください。

2017-08-28 04:44 UTC, taguchi-k commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +@property UIAlertAction * cancelButton;
プロパティにしなくでも大丈夫です。

2017-08-28 04:44 UTC, taguchi-k commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +@property UIAlertAction * okButton;
プロパティにしなくでも大丈夫です。

2017-08-28 04:44 UTC, taguchi-k commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +-(void)initAlertController {
インスタンスを返さないメソッドで`init`を使わないようにしてください。

2017-08-28 06:17 UTC, ddd503 commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +@property UIAlertAction * cancelButton;
プロパティにせず、viewDidLoad内で作成し、その中でのみ使用するように変更しました。

2017-08-28 06:17 UTC, ddd503 commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +@property UIAlertAction * okButton;
プロパティにせず、viewDidLoad内で作成し、その中でのみ使用するように変更しました。

2017-08-28 06:17 UTC, ddd503 commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +-(void)initAlertController {
viewDidLoad内でAlertControllerとAlertActionの作成を行うよう変更致しました。

2017-08-28 06:30 UTC, ddd503 commented
@taguchi-k 
#9の課題につきまして、レビュー頂いた箇所を修正させて頂きました。
お時間ある際に再度レビューをお願い致します。

2017-08-29 15:39 UTC, taguchi-k reviewed
@ddd503 
レビューOKです。
※軽微な指摘をしているのでご確認ください。

2017-08-29 15:39 UTC, taguchi-k commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +    self.alertController = [UIAlertController
@ddd503 
【参考：修正不要です】
`alertController`の設定についてはメソッドに切り出していたほうが`viewDidLoad `内の記載がすっきりしていいと思います。
以前`initAlertController`としていたところのメソッド名だけ変えてあげればOKです。

2017-08-29 15:45 UTC, ddd503 commented on STVProject2-1-4/STVProject2-1-4/ViewController.m
> +    self.alertController = [UIAlertController
@taguchi-k 
ご指摘ありがとうございます。
今後着手する課題に関しましては、メソッドの切り出し、viewDidLoad内の整理、を意識して書いていきます。
マージさせて頂きます。

2017-08-29 15:46 UTC, merged