Fiexd. #10の課題の修正が完了しました。
ddd503/objc-basic pull request #41
Opened 2017-08-22 03:02 UTC by ddd503

@taguchi-k
#10の課題の修正が完了しました。
お時間ある際にレビューをお願い致します。

2017-08-27 05:47 UTC, ddd503 commented
以前の課題にてレビュー頂いた箇所を修正しております。
お時間ある際にレビューをお願い致します。

2017-08-28 04:48 UTC, taguchi-k requested changes
@ddd503 
レビューしました。確認・対応してください。

2017-08-28 04:48 UTC, taguchi-k commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +- (void)initAlertController{
インスタンスを返さないメソッドで`init`を使わないようにしてください。

2017-08-28 04:48 UTC, taguchi-k commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * faceBookAction;
プロパティにしなくでも大丈夫です。

2017-08-28 04:48 UTC, taguchi-k commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * twitterAction;
プロパティにしなくでも大丈夫です。

2017-08-28 04:48 UTC, taguchi-k commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * lineAction;
プロパティにしなくでも大丈夫です。

2017-08-28 04:48 UTC, taguchi-k commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * cancelAction;
プロパティにしなくでも大丈夫です。

2017-08-28 06:25 UTC, ddd503 commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * faceBookAction;
プロパティにせず、viewDidLoadにて作成、使用するように変更致しました。

2017-08-28 06:25 UTC, ddd503 commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * twitterAction;
プロパティにせず、viewDidLoadにて作成、使用するように変更致しました。

2017-08-28 06:25 UTC, ddd503 commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * lineAction;
プロパティにせず、viewDidLoadにて作成、使用するように変更致しました。

2017-08-28 06:25 UTC, ddd503 commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +@property UIAlertAction * cancelAction;
プロパティにせず、viewDidLoadにて作成、使用するように変更致しました。

2017-08-28 06:27 UTC, ddd503 commented on STVProject2-1-5/STVProject2-1-5/ViewController.m
> +- (void)initAlertController{
インスタンスを戻す必要がなかったため、viewDidLoadにてAlertControllerとその設定の作成を行うように変更しました。

2017-08-28 06:30 UTC, ddd503 commented
@taguchi-k 
#10 の課題につきまして、レビュー頂いた箇所を修正させて頂きました。
お時間ある際に再度レビューをお願い致します。

2017-08-29 15:41 UTC, taguchi-k commented
@ddd503 
レビューOkです。
※アラートの場合と同様の軽微な指摘ができる状態ではあります。（修正不要です）

2017-08-29 15:47 UTC, ddd503 commented
@taguchi-k 
ご指摘ありがとうございます。
#9 の課題同様、今後は、メソッドの切り出し、viewDidLoad内の整理、を意識して書いていきます。
マージさせて頂きます。

2017-08-29 15:47 UTC, merged